src/main/java/pl/mateusz/wypozyczalniaplyt/controllers/MemberBean.java
package pl.mateusz.wypozyczalniaplyt.controllers;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import org.primefaces.context.RequestContext;

import pl.mateusz.wypozyczalniaplyt.domains.Member;
import pl.mateusz.wypozyczalniaplyt.services.GenreService;
import pl.mateusz.wypozyczalniaplyt.services.MemberService;
import pl.mateusz.wypozyczalniaplyt.utils.Logging;

@ManagedBean
@RequestScoped
public class MemberBean {
	

	private Member member = new Member();	
	private Member edited = new Member();
		
	private boolean memberAdded = false;
	
	private List<Member> mlist;
	
	public Member getEdited() {
		return edited;
	}


	public void setEdited(Member edited) {
		this.edited = edited;
	}


	public Member getMember() {
		return member;
	}


	public void setMember(Member member) {
		this.member = member;
	}

	public void addMember() {
		MemberService.addMember(member);
		this.memberAdded = true;
		Logging.logInfo("adding member: " + member);
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Dodano do bazy.", "Dodano do bazy."));
	}
	
	public List<Member> getMemberList() {
		mlist = MemberService.getMemberList();
		return mlist;
	}


	public boolean isMemberAdded() {
		return memberAdded;
	}


	public void setMemberAdded(boolean memberAdded) {
		this.memberAdded = memberAdded;
	}




	
	public void editMember() {
		Logging.logInfo("tu je edycja ");
		FacesContext fc = FacesContext.getCurrentInstance();
		
		Integer id = Integer.parseInt(fc.getExternalContext().getRequestParameterMap().get("id"));
		edited.setId(id);
				
		Logging.logInfo(edited.toString());
		
		MemberService.editMember(edited);
	}
	
	public void deleteMember() {
		
		FacesContext fc = FacesContext.getCurrentInstance();
		RequestContext rq = RequestContext.getCurrentInstance();
		Integer id = Integer.parseInt(fc.getExternalContext().getRequestParameterMap().get("id"));
		member.setId(id);
		
		if (MemberService.deleteMember(member)) {
			Logging.logInfo("deleted member of id: " + member.getId());
			rq.execute("deleteDlg.hide()");
		}

		
	}

	
}

src/main/webapp/views/member/addMember.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<h:form id="addForm" prependId="false">
	 
		<p:panelGrid columns="2" style="margin: 0 auto; text-align: center"
			id="addFormPanelGrid">

			<f:facet name="header">
	        	Dodawanie nowego członka
	    	</f:facet>

			<h:outputText value="Imię: *" />
			<p:inputText id="firstName" label="Firstname"
				value="#{memberBean.member.firstName}" 
				required="true">
				<f:validator validatorId="requiredValidator" />
				<f:validateLength minimum="1" maximum="255" for="firstName" />
				</p:inputText>

			<h:outputText value="Nazwisko: *" />
			<p:inputText id="surname" label="Surname"
				value="#{memberBean.member.surname}" 
				required="true" validator="requiredValidator">
				<f:validateLength minimum="1" maximum="255" for="surname" />
				</p:inputText>

			<h:outputText value="E-mail: *" />
			<p:inputText id="email" label="E-mail"
				value="#{memberBean.member.email}" 
				required="true"
				>
				<f:validateLength minimum="1" maximum="255" for="email" />
				<f:validator validatorId="emailValidator" />
				<f:validator validatorId="requiredValidator" />
				</p:inputText>

			<p:commandButton value="Dodaj"
				actionListener="#{memberBean.addMember}" update="output" />
			<p:commandButton value="Wyczyść" update="output,addFormPanelGrid"
				process="@this"
				actionListener="#{menuBean.resetInput('contentForm:addForm')}" />
				 
		</p:panelGrid>
		

		<h:panelGroup layout="block" id="output" style="margin: 0 auto;">
			<p:messages id="messages" />
		</h:panelGroup>
	</h:form>



</ui:composition>

src/main/webapp/views/member/deleteMember.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:form id="memberForm" prependId="false">

	<!-- Domyślny widok - pokazuje liste członków i możliwe akcje do wykonania -->
		<p:dataTable var="member" value="#{memberBean.memberList}"
			emptyMessage="Brak rekordów w bazie." id="mDataTable">
			
			<f:facet name="header">  
            	Lista członków wypożyczalni
       		 </f:facet> 
			<p:column headerText="Imię">
				<h:outputText value="#{member.firstName}" />
			</p:column>
			<p:column headerText="Nazwisko">
				<h:outputText value="#{member.surname}" />
			</p:column>
			<p:column headerText="E-mail">
				<h:outputText value="#{member.email}" />
			</p:column>
			<p:column>
				<p:commandButton value="Usuń" update=":contentForm:memberForm:deleteForm:delete" oncomplete="deleteDlg.show()" process="@this">
					<f:setPropertyActionListener value="#{member}" target="#{memberBean.member}" />
				</p:commandButton>
			</p:column>
		</p:dataTable>
	
	<!-- Formularz kasowania członka -->
	<p:dialog header="Potwierdź usunięcie członka" id="deleteDlg" widgetVar="deleteDlg" resizable="true"	modal="true">
	
		<!--  zamkniecie formularza powoduje aktualizacje tabelki oraz zresetowanie danych wejsciowych z formularza -->
		<p:ajax event="close" update="mDataTable" listener="#{menuBean.resetInput('contentForm:memberForm:deleteForm')}"/>  

		<h:form id="deleteForm">
			<p:panelGrid columns="2" style="margin: 0 auto; text-align: center"	id="delete">
				<h:outputText value="Imię"  />
				<h:outputText value="#{memberBean.member.firstName}"  />
				
				<h:outputText value="Nazwisko"  />
				<h:outputText value="#{memberBean.member.surname}"  />
				
				<h:outputText value="Email"  />
				<h:outputText value="#{memberBean.member.email}"  />
				
				<p:commandButton value="Usuń" process="@form" action="#{memberBean.deleteMember}">
					<f:param name="id" value="#{memberBean.member.id}" />		
				</p:commandButton>
				
				<p:commandButton value="Anuluj" onclick="deleteDlg.close()" >
		
				</p:commandButton>
				
						
			</p:panelGrid>
		
		</h:form>
	</p:dialog>
</h:form>
</ui:composition>

src/main/webapp/views/member/editMember.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:form id="memberForm" prependId="false">

	<!-- Domyślny widok - pokazuje liste członków i możliwe akcje do wykonania -->
		<p:dataTable var="member" value="#{memberBean.memberList}"
			emptyMessage="Brak rekordów w bazie." id="mDataTable">
			<f:facet name="header">  
            	Lista członków wypożyczalni
       		 </f:facet>  
			<p:column headerText="Imię">
				<h:outputText value="#{member.firstName}" />
			</p:column>
			<p:column headerText="Nazwisko">
				<h:outputText value="#{member.surname}" />
			</p:column>
			<p:column headerText="E-mail">
				<h:outputText value="#{member.email}" />
			</p:column>
			<p:column>
				<p:commandButton value="Edytuj" update=":contentForm:memberForm:editForm:edit" oncomplete="editDlg.show()" process="@this">  
                	<f:setPropertyActionListener value="#{member}" target="#{memberBean.member}" />  
                </p:commandButton>
			</p:column>
		</p:dataTable>

	
	<!-- Formularz edycji -->
	<p:dialog header="Edycja członka" id="editDlg" widgetVar="editDlg" resizable="true"	modal="true">
		<p:ajax event="close" update="editDlg,mDataTable" listener="#{menuBean.resetInput('contentForm:memberForm:editForm')}"/>  
		<h:form id="editForm">
			<p:panelGrid columns="2" style="margin: 0 auto; text-align: center"
				id="edit">
	 
				<h:outputText value="Imię: *"  />
				<p:inputText id="firstName" label="Firstname"
					value="#{memberBean.member.firstName}" 
					required="true" validator="requiredValidator">
					</p:inputText>
	
				<h:outputText value="Nazwisko: *" />
				<p:inputText id="surname" label="Surname"
					value="#{memberBean.member.surname}" 
					required="true" validator="requiredValidator"/>
	
				<h:outputText value="E-mail: *" />
				<p:inputText id="email" label="E-mail"
					value="#{memberBean.member.email}" 
					required="true" validator="requiredValidator">
					<f:validator validatorId="emailValidator" />
					</p:inputText>
	
				<p:commandButton value="Edytuj" update="outInfo" process="@form" action="#{memberBean.editMember}"
				oncomplete="if (!args.validationFailed) editDlg.hide()">
					<f:param name="id" value="#{memberBean.member.id}" />
					<f:param name="email" value="#{memberBean.member.email}" />
					<f:setPropertyActionListener value="#{memberBean.member}" target="#{memberBean.edited}" />
				</p:commandButton>
				
			</p:panelGrid>
			
			<h:panelGroup layout="block" id="outInfo" style="margin: 0 auto;">
				<p:messages id="messages" />
			</h:panelGroup>
				
		</h:form>
			
	</p:dialog>
</h:form>
</ui:composition>