src/main/java/pl/mateusz/wypozyczalniaplyt/controllers/EditMovieBean.java
package pl.mateusz.wypozyczalniaplyt.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.primefaces.context.RequestContext;

import pl.mateusz.wypozyczalniaplyt.domains.Genre;
import pl.mateusz.wypozyczalniaplyt.domains.Movie;
import pl.mateusz.wypozyczalniaplyt.services.GenreService;
import pl.mateusz.wypozyczalniaplyt.services.MovieService;
import pl.mateusz.wypozyczalniaplyt.utils.Logging;

@ManagedBean
@ViewScoped
public class EditMovieBean implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Movie movie = new Movie();
	private List<Movie> movieList = MovieService.getMovieList();
	private List<String> selectedGenresId; // przerobic to na arrayliste i powinno zadzialac
	
	public void processTempGenreChange(Movie m) {
		Logging.logInfo("processTempGenreChange - movie name: " + m.getTitle());
		Logging.logInfo("processTempGenreChange - genre list size: " + m.getGenres().size());
		selectedGenresId = new ArrayList<String>();
		for (Genre g: m.getGenres()) {
			selectedGenresId.add(Integer.toString(g.getId()));
		}

		
	}	
	
	public void processNewGenres(List<String> genreIds) {
		Logging.logInfo("processNewGenres - " + genreIds.size());
		
		Set<Genre> newGenres = new HashSet<Genre>();
		
		for (String s: genreIds) {
			Genre g = GenreService.getGenreById(Integer.parseInt(s));
			newGenres.add(g);
		}
		
		Logging.logInfo("processNewGenres - " + newGenres.size());
		
		movie.setGenres(newGenres);
	}

	public void editMovie(Movie m) {
		if (m.getGenres().size() == 0) {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nie podano gatunków.", "Nie podano gatunków."));
			RequestContext context = RequestContext.getCurrentInstance();  
	        context.addCallbackParam("validationFailed", true);    //basic parameter  
		} else {
			MovieService.editMovie(m);
		}
	}
	
	public Movie getMovie() {
		return movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	public List<String> getSelectedGenresId() {
		return selectedGenresId;
	}

	public void setSelectedGenresId(List<String> selectedGenresId) {
		this.selectedGenresId = selectedGenresId;
	}
	
	public EditMovieBean() {
		
	}

	public List<Movie> getMovieList() {
		return movieList;
	}

	public void setMovieList(List<Movie> movieList) {
		this.movieList = movieList;
	}

}

src/main/java/pl/mateusz/wypozyczalniaplyt/controllers/GenreBean.java
package pl.mateusz.wypozyczalniaplyt.controllers;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import pl.mateusz.wypozyczalniaplyt.domains.Genre;
import pl.mateusz.wypozyczalniaplyt.services.GenreService;
import pl.mateusz.wypozyczalniaplyt.utils.Logging;

@ManagedBean
@RequestScoped
public class GenreBean {
			
		
	private Genre genre = new Genre();
	private Genre edited = new Genre();
	
	private List<Genre> gList;
	
	private boolean exists = false;
	private boolean genreAdded = false;

	public Genre getGenre() {
		return genre;
	}


	public void setGenre(Genre genre) {
		this.genre = genre;
	}


	public boolean isGenreAdded() {
		return genreAdded;
	}
	
	public List<Genre> getGlist() {
		gList = GenreService.getGenreList();
		return gList;
	}
	
	


	public void setgList(List<Genre> gList) {
		this.gList = gList;
	}


	public void setGenreAdded(boolean genreAdded) {
		this.genreAdded = genreAdded;
	}

	public void addGenre() {
		if (!exists) {
			GenreService.addGenre(genre);
			this.genreAdded = true;
			Logging.logInfo("adding genre: " + genre);
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Dodano do bazy.", "Dodano do bazy."));
		}
	}
	
	public void editGenre() {
		Logging.logInfo("editing genre");
		FacesContext fc = FacesContext.getCurrentInstance();
		
        Integer id = Integer.parseInt(fc.getExternalContext().getRequestParameterMap().get("id"));
		edited.setId(id);
				
		Logging.logInfo(edited.toString());
		
		if (!exists) {
			GenreService.editGenre(edited);
		}
		
	}

	public void deleteGenre() {
		
		GenreService.deleteGenre(genre);
		FacesContext fc = FacesContext.getCurrentInstance();
		
		Integer id = Integer.parseInt(fc.getExternalContext().getRequestParameterMap().get("id"));
		genre.setId(id);
		
		Logging.logInfo("deleting genre id => " + genre.getId());
		
		GenreService.deleteGenre(genre);
	}

	public Genre getEdited() {
		return edited;
	}


	public void setEdited(Genre edited) {
		this.edited = edited;
	}
	
}

src/main/java/pl/mateusz/wypozyczalniaplyt/controllers/MovieBean.java
package pl.mateusz.wypozyczalniaplyt.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import pl.mateusz.wypozyczalniaplyt.domains.Genre;
import pl.mateusz.wypozyczalniaplyt.domains.Movie;
import pl.mateusz.wypozyczalniaplyt.services.GenreService;
import pl.mateusz.wypozyczalniaplyt.services.MovieService;
import pl.mateusz.wypozyczalniaplyt.utils.Logging;

@ManagedBean
@RequestScoped
public class MovieBean implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	// TODO: przerobic edycje i dodawanie gatunkow na datatable z multiple check lista
	private Movie movie = new Movie();
	
	private List<Movie> movieList = MovieService.getMovieList();
	private List<String> selectedGenresId; // przerobic to na arrayliste i powinno zadzialac
	private Set<Genre> selectedGenres;
	
	private String[] testArray = {"1","2","3"};
	private String[] testArraySelected = {"2","1"};
	
	private boolean movieAdded = false;

	public MovieBean() {
		
	}
	public Movie getMovie() {
		return movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	public boolean isMovieAdded() {
		return movieAdded;
	}

	public void setMovieAdded(boolean movieAdded) {
		this.movieAdded = movieAdded;
	}
	
	private Set<Genre> genreParser() {
		
		Set<Genre> movieGenreList = new HashSet<Genre>(0);
		for (int i=0; i<this.selectedGenresId.size(); i++) {
			Genre g = new Genre();
			
			int id = Integer.parseInt(this.selectedGenresId.get(i));
			g = GenreService.getGenreById(id);
			
			movieGenreList.add(g);
		}
		return movieGenreList;
	}
	public void addMovie() {
		System.out.println("addmovie");
		System.out.println("movie id: " + movie.getId());
		System.out.println("movie title: " + movie.getTitle());
		System.out.println("movie genres:");

		movie.setGenres(genreParser());
		
		if (movie.getGenres().size() == 0) {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nie podano gatunków.", "Nie podano gatunków."));
		} else {
			for (Genre g: movie.getGenres()) {
				System.out.println(g.getName());
			}
			System.out.println("movie dvd release: " + movie.getDvdReleaseDate());
			MovieService.addMovie(movie);
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Dodano do bazy.", "Dodano do bazy."));
			
		}
		
	}
	
	public void convertIdToObject() {
		setSelectedGenres(genreParser());
	}
	
	public void populateSelectedGenres() {
		Logging.logInfo("populating genres in selected movie");
		FacesContext fc = FacesContext.getCurrentInstance();
		
		Integer idMovieToEdit = Integer.parseInt(fc.getExternalContext().getRequestParameterMap().get("id"));
		Movie m = MovieService.getMovieById(idMovieToEdit);
		
		Logging.logInfo("current number of genres: " + m.getGenres().size());
	

	selectedGenresId = new ArrayList<String>();
	
		for (Genre g: movie.getGenres()) {
			selectedGenresId.add(Integer.toString(g.getId()));
		}
	}
	
	public void processTempGenreChange() {
		
		for (int i=0; i<selectedGenresId.size(); i++) {
			System.out.println(selectedGenresId.get(i));
		}
		Logging.logInfo("previous genre size: " + movie.getGenres().size());
		movie.setGenres(genreParser());
		
		Logging.logInfo("current genre size: " + movie.getGenres().size());
		
		
	}
	
	public void deleteMovie(Movie m) {
		
		MovieService.deleteMovie(m);
	}

	public List<Movie> getMovieList() {
		return movieList;
	}

	public void setMovieList(List<Movie> movieList) {
		this.movieList = movieList;
	}

	public List<String> getSelectedGenresId() {
		Logging.logInfo("getSelectedGenresId");
		return selectedGenresId;
	}

	public void setSelectedGenresId(List<String> selectedGenresId) {
		this.selectedGenresId = selectedGenresId;
	}

	public Set<Genre> getSelectedGenres() {
		return selectedGenres;
	}

	public void setSelectedGenres(Set<Genre> selectedGenres) {
		this.selectedGenres = selectedGenres;
	}

	public String[] getTestArray() {
		return testArray;
	}

	public void setTestArray(String[] testArray) {
		this.testArray = testArray;
	}

	public String[] getTestArraySelected() {
		return testArraySelected;
	}

	public void setTestArraySelected(String[] testArraySelected) {
		this.testArraySelected = testArraySelected;
	}

	
	
}

src/main/webapp/views/movie/addMovie.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<h:form id="addForm" prependId="false">
	 
		<p:panelGrid columns="3" style="margin: 0 auto; text-align: center"
			id="addFormPanelGrid">

			<f:facet name="header">
	        	Dodawanie nowego filmu
	    	</f:facet>

			<h:outputText value="Tytuł: *" />
			<p:inputText id="title" label="title"
				value="#{movieBean.movie.title}" 
				required="true">
				<f:validator validatorId="requiredValidator" />
				</p:inputText>
			<h:outputText value="" />

			<h:outputText value="Gatunek: *" />
			<p:outputPanel id="genres">
			
				<p:dataList value="#{movieBean.selectedGenres.toArray()}" var="item">
					#{item.name}
					
    			</p:dataList>
			</p:outputPanel>
			
			<p:commandButton value="Wybierz"
				oncomplete="chooseGenres.show()" process="@this"
				/>
				
			

			<h:outputText value="Premiera na DVD: *" />
			<p:calendar value="#{movieBean.movie.dvdReleaseDate}" showButtonPanel="true" required="true" label="dvd_release_date" navigator="true" 
				pattern="dd/MM/yyyy"/>
				<h:outputText value="" />

			<p:commandButton value="Dodaj"
				actionListener="#{movieBean.addMovie}" update="output" />
			<p:commandButton value="Wyczyść" update="output,addFormPanelGrid"
				process="@this"
				actionListener="#{menuBean.resetInput('contentForm:addForm')}" />			 
		</p:panelGrid>

		<h:panelGroup layout="block" id="output" style="margin: 0 auto;">
			<p:messages id="messages" />
		</h:panelGroup>
	
	<!-- dialogbox wyswietlajacy menu wyboru gatunku filmu -->	
	<h:form id="chooseGenresForm">
		<p:dialog header="Wybierz gatunki" id="chooseGenres" widgetVar="chooseGenres" resizable="true"	modal="true">
	
		
			<p:selectManyCheckbox layout="pageDirection" value="#{movieBean.selectedGenresId}" >
				
				<f:selectItems value="#{genreBean.glist}" var="genre" itemLabel="#{genre.name}"  itemValue="#{genre.id}"/>
			</p:selectManyCheckbox>
			
			<p:commandButton value="Zatwierdź" oncomplete="chooseGenres.hide()" update=":contentForm:addForm:genres" process="@form"
			actionListener="#{movieBean.convertIdToObject}" />
			
		
		
		</p:dialog>
	</h:form>
	</h:form>



</ui:composition>

src/main/webapp/views/movie/deleteMovie.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:form id="movieForm" prependId="false">

	<!-- Domyślny widok - pokazuje liste członków i możliwe akcje do wykonania -->
		<p:dataTable var="movie" value="#{movieBean.movieList}"
			emptyMessage="Brak rekordów w bazie." id="mDataTable">
			<f:facet name="header">  
            	Lista filmów w wypożyczalni
       		 </f:facet>  
			<p:column headerText="Tytuł">
				<h:outputText value="#{movie.title}" />
			</p:column>
			<p:column headerText="Gatunki">
				<ui:repeat value="#{movie.genres.toArray()}" var="genre">
					<h:outputText value="#{genre.name}" /> <br />
				</ui:repeat>
			</p:column>
			<p:column headerText="Data wydania na DVD">
				<h:outputText value="#{movie.dvdReleaseDate}">
					<f:convertDateTime type="date" pattern="yyyy-MM-dd" />
				</h:outputText>
			</p:column>
			<p:column headerText="Dostępny">
					<h:outputText styleClass="ui-icon ui-icon-check" rendered="#{movie.available == true}"/>
					<h:outputText styleClass="ui-icon ui-icon-close" rendered="#{movie.available == false}"/>
			</p:column>
			<p:column>
				<p:commandButton value="Usuń" update=":contentForm:movieForm:deleteForm:delete" oncomplete="deleteDlg.show()" process="@this"
				action="#{movieBean.setMovie(movie)}">  
                	
                </p:commandButton>
			</p:column>
		</p:dataTable>
	
	<!-- Formularz kasowania członka -->
	<p:dialog header="Potwierdź usunięcie filmu" id="deleteDlg" widgetVar="deleteDlg" resizable="true"	modal="true">
	
		<!--  zamkniecie formularza powoduje aktualizacje tabelki oraz zresetowanie danych wejsciowych z formularza -->
		<p:ajax event="close" update="mDataTable" listener="#{menuBean.resetInput('contentForm:movieForm:deleteForm')}"/>  

		<h:form id="deleteForm">
			<p:panelGrid columns="2" style="margin: 0 auto; text-align: center"	id="delete">
				<h:outputText value="Tytuł"  />
				<h:outputText value="#{movieBean.movie.title}"  />
				
				<h:outputText value="Gatunki"  />
				<ui:repeat value="#{movieBean.movie.genres.toArray()}" var="genre">
					<h:outputText value="#{genre.name}" /> <br />
				</ui:repeat>
				
				<h:outputText value="Data wydania na DVD"  />
				<h:outputText value="#{movieBean.movie.dvdReleaseDate}"  />
				
				<p:commandButton value="Usuń" process="@form" action="#{movieBean.deleteMovie(movie)}" oncomplete="deleteDlg.hide()" update=":contentForm:movieForm:mDataTable">
				</p:commandButton>
				
				<p:commandButton value="Anuluj" onclick="deleteDlg.close()" >
		
				</p:commandButton>
				
						
			</p:panelGrid>
		
		</h:form>
	</p:dialog>
</h:form>
</ui:composition>

src/main/webapp/views/movie/editMovie.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:form id="movieForm" prependId="false">

	<!-- Domyślny widok - pokazuje liste członków i możliwe akcje do wykonania -->
		<p:dataTable var="movie" value="#{movieBean.movieList}"
			emptyMessage="Brak rekordów w bazie." id="mDataTable">
			<f:facet name="header">  
            	Lista filmów w wypożyczalni
       		 </f:facet>  
			<p:column headerText="Tytuł">
				<h:outputText value="#{movie.title}" />
			</p:column>
			<p:column headerText="Gatunki">
				<ui:repeat value="#{movie.genres.toArray()}" var="genre">
					<h:outputText value="#{genre.name}" /> <br />
				</ui:repeat>
			</p:column>
			<p:column headerText="Data wydania na DVD">
				<h:outputText value="#{movie.dvdReleaseDate}">
					<f:convertDateTime type="date" pattern="yyyy-MM-dd" />
				</h:outputText>
			</p:column>
			<p:column headerText="Dostępny">
					<h:outputText styleClass="ui-icon ui-icon-check" rendered="#{movie.available == true}"/>
					<h:outputText styleClass="ui-icon ui-icon-close" rendered="#{movie.available == false}"/>
			</p:column>
			<p:column>
				<p:commandButton value="Edytuj" update=":contentForm:movieForm:editForm:edit" oncomplete="editDlg.show()" process="@this"
				action="#{editMovieBean.setMovie(movie)}">  
                	
                </p:commandButton>
			</p:column>
		</p:dataTable>
		
	<!-- Formularz edycji -->
	<p:dialog header="Edycja filmu" id="editDlg" widgetVar="editDlg" resizable="true"	modal="true">
		<p:ajax event="close" update="mDataTable" listener="#{menuBean.resetInput('contentForm:movieForm:editForm')}"/>  
		<h:form id="editForm">
			<p:panelGrid columns="3" style="margin: 0 auto; text-align: center"
				id="edit">
	 
				<h:outputText value="Tytuł: *"  />
				<p:inputText id="title" label="Title"
					value="#{editMovieBean.movie.title}" required="true">
					</p:inputText>
				<h:outputText value="" />
					
				<h:outputText value="Gatunki: " />
				<ui:repeat value="#{editMovieBean.movie.genres.toArray()}" var="genre">
					<h:outputText value="#{genre.name}" /> <br />
				</ui:repeat>
				
				
				
				<p:commandButton value="Wybierz"
				oncomplete="chooseGenres.show()" process="@form"
				action="#{editMovieBean.processTempGenreChange(editMovieBean.movie)}"
				update=":contentForm:movieForm:chooseGenresForm:chooseGenres">
				</p:commandButton>
				
				
				<h:outputText value="Premiera na DVD: *" />
					<p:calendar value="#{editMovieBean.movie.dvdReleaseDate}" showButtonPanel="true" required="true" label="dvd_release_date" 
					navigator="true" pattern="dd/MM/yyyy"/>
				<h:outputText value="" />
				
				<h:outputText value="Dostępny: *" />
					<h:outputText styleClass="ui-icon ui-icon-check" rendered="#{editMovieBean.movie.available == true}"/>
					<h:outputText styleClass="ui-icon ui-icon-close" rendered="#{editMovieBean.movie.available == false}"/>
				<h:outputText value="" />
				
	
				<p:commandButton value="Edytuj" update="outInfo" process="@form" action="#{editMovieBean.editMovie(editMovieBean.movie)}"
				oncomplete="if (!args.validationFailed) editDlg.hide()" >
				</p:commandButton>
				
			</p:panelGrid>
			
			<h:panelGroup layout="block" id="outInfo" style="margin: 0 auto;">
				<p:messages id="messages" />
			</h:panelGroup>
				
		</h:form>
		
	
			
	</p:dialog>
	
	<!-- dialogbox wyswietlajacy menu wyboru gatunku filmu -->	
		<h:form id="chooseGenresForm">
			
			<p:dialog header="Wybierz gatunki" id="chooseGenres" widgetVar="chooseGenres" resizable="true"	modal="true">
		
				<p:selectManyCheckbox layout="pageDirection" value="#{editMovieBean.selectedGenresId}" >
					
					<f:selectItems value="#{genreBean.glist}" var="genre" itemLabel="#{genre.name}" itemValue="#{genre.id}" />
				</p:selectManyCheckbox>
				
				<p:commandButton value="Zatwierdź" oncomplete="chooseGenres.hide()" update=":contentForm:movieForm:editForm:edit" process="@form"
				action="#{editMovieBean.processNewGenres(editMovieBean.selectedGenresId)}"
				
				/>		
			
			</p:dialog>
		</h:form>
</h:form>
</ui:composition>